# ==========================================
# ReaLiTy - Weather Adaptation Config
# ==========================================

mode: weather

projection:
  H: 64
  W: 1024
  fov_up: 2.0 #KITTI
  fov_down: -25.0 #KITTI

intensity:
  mean: 0.0158 #CADC Snow
  std: 0.0462  #CADC Snow

weather:
  atm_model: snow      # change to "rain" if needed
  precipitation_rate: 30  # mm/hr